services:
  db:
    image: mysql:8.0
    restart: always
    container_name: "library_db_container"
    environment:
      MYSQL_DATABASE: booksdb
      MYSQL_ROOT_PASSWORD: Juni0rt1t0
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - app-network

  django_app:
    image: django_app
    build:
      context: ./mysite
    command: gunicorn mysite.wsgi --bind :8000
    container_name: "library_django_container"
    restart: always
    depends_on:
      - db
    env_file:
      - "./mysite/mysite/.env"
    expose:
      - 8000
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: "library_redis_container"
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - app-network

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "library_nginx_container"
    restart: always
    ports:
      - 80:80
    depends_on:
      - django_app
    volumes:
      - ./mysite/staticfiles:/mysite/staticfiles
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
