# Generated by Django 5.1.7 on 2025-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('language', models.CharField(max_length=10)),
                ('authors', models.TextField()),
                ('subjects', models.TextField()),
                ('locc', models.CharField(blank=True, max_length=100, null=True)),
                ('bookshelves', models.TextField()),
            ],
        ),
    ]
